"""
kantorku CLI — Command-line interface.

Commands:
    kantorku serve           Start the server (default)
    kantorku init            Scaffold a new kantorku project
    kantorku worker list     List available workers
    kantorku config validate Validate kantorku.toml
    kantorku run             Run a one-shot task
    kantorku version         Show version
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path


def cmd_serve(args: argparse.Namespace) -> None:
    """Start the kantorku server."""
    import uvicorn
    from kantorku.server import create_office

    config_path = getattr(args, "config", None)
    office = create_office(config_path)

    uvicorn.run(
        "kantorku.server:app",
        host=getattr(args, "host", "0.0.0.0"),
        port=getattr(args, "port", 8000),
        reload=getattr(args, "reload", False),
        lifespan="on",
    )


def cmd_init(args: argparse.Namespace) -> None:
    """Scaffold a new kantorku project."""
    project_dir = Path(getattr(args, "name", "my-office"))
    project_dir.mkdir(parents=True, exist_ok=True)

    # Create kantorku.toml
    toml_content = '''# kantorku configuration
# Generated by `kantorku init`

[conductor]
model = "anthropic/claude-opus-4-6"

[providers.anthropic]
api_key = "${ANTHROPIC_API_KEY}"

[providers.ollama]
base_url = "http://localhost:11434"

[workers.coder_frontend]
model = "anthropic/claude-sonnet-4-6"
squad = "coding"
role = "React/CSS/UI specialist"

[workers.coder_backend]
model = "ollama/llama3"
squad = "coding"
role = "Python/Rust/Systems specialist"

[workers.intake]
model = "ollama/llama3"
squad = "translation"
role = "Message parser"

[workers.narrator]
model = "ollama/llama3"
squad = "translation"
role = "Output formatter"

[pool]
model = "ollama/llama3"
instances = 1

[memory]
ring1_path = "data/ring1.duckdb"
ring2_path = "data/ring2.db"
ring3_enabled = false

[server]
host = "0.0.0.0"
port = 8000
'''

    (project_dir / "kantorku.toml").write_text(toml_content)

    # Create data directory
    (project_dir / "data").mkdir(exist_ok=True)

    # Create custom workers directory
    (project_dir / "workers").mkdir(exist_ok=True)

    # Create a simple example
    example_content = '''"""Example: Using kantorku programmatically."""
import asyncio
from kantorku import Office, Hooks, HookType

async def main():
    # Create office with hooks
    hooks = Hooks()

    @hooks.on(HookType.ON_TASK_COMPLETED)
    async def on_done(event):
        print(f"Task completed: {event.get('task_id', 'unknown')}")

    office = Office(hooks=hooks)

    # Configure providers
    office.configure_provider("ollama", base_url="http://localhost:11434")

    # Hire workers
    office.hire_worker("coder_backend", model="ollama/llama3", role="Backend developer")

    # Initialize
    await office.initialize()

    # Run a task
    result = await office.run("Write a Python function to calculate fibonacci", auto_accept=True)
    print(result)

    await office.shutdown()

if __name__ == "__main__":
    asyncio.run(main())
'''

    (project_dir / "example.py").write_text(example_content)

    print(f"Created kantorku project in ./{project_dir}/")
    print(f"  - {project_dir}/kantorku.toml  (configuration)")
    print(f"  - {project_dir}/data/          (memory storage)")
    print(f"  - {project_dir}/workers/       (custom workers)")
    print(f"  - {project_dir}/example.py     (example script)")
    print()
    print("Next steps:")
    print(f"  1. cd {project_dir}")
    print("  2. Edit kantorku.toml with your API keys")
    print("  3. Run: kantorku serve --config kantorku.toml")


def cmd_worker_list(args: argparse.Namespace) -> None:
    """List available workers."""
    from kantorku.worker.registry import WorkerRegistry
    from kantorku.events.bus import EventBus
    from kantorku.providers.router import ProviderRouter

    router = ProviderRouter()
    bus = EventBus()
    registry = WorkerRegistry(router=router, bus=bus)

    # Discover built-in workers
    workers_dir = Path(__file__).parent.parent / "workers"
    if workers_dir.exists():
        registry.discover_workers(workers_dir)

    # Discover external workers
    config_path = getattr(args, "config", None)
    if config_path:
        external_dir = Path(config_path).parent / "workers"
        if external_dir.exists():
            registry.discover_workers(external_dir)

    workers = registry.list_workers()

    if not workers:
        print("No workers found.")
        return

    # Group by squad
    squads: dict[str, list[dict]] = {}
    for w in workers:
        squad = w.get("squad", "unknown")
        if squad not in squads:
            squads[squad] = []
        squads[squad].append(w)

    print(f"Available workers ({len(workers)} total):\n")
    for squad, members in sorted(squads.items()):
        print(f"  [{squad}]")
        for w in members:
            model = w.get("model", "N/A")
            status = w.get("status", "N/A")
            print(f"    - {w['id']:25s} model={model:30s} status={status}")
        print()


def cmd_config_validate(args: argparse.Namespace) -> None:
    """Validate a kantorku.toml configuration file."""
    config_path = getattr(args, "config", None)
    if not config_path:
        print("Error: --config path required for validation")
        sys.exit(1)

    path = Path(config_path)
    if not path.exists():
        print(f"Error: Config file not found: {config_path}")
        sys.exit(1)

    try:
        from kantorku.config.settings import KantorkuConfig
        config = KantorkuConfig.from_toml(config_path)
        config.resolve_env_vars()

        errors = []
        warnings = []

        # Check conductor model
        if not config.conductor_model:
            errors.append("conductor.model is required")
        elif "/" not in config.conductor_model:
            errors.append(f"conductor.model must be 'provider/model' format, got: {config.conductor_model}")

        # Check workers
        if not config.workers:
            warnings.append("No workers configured")

        for wid, wcfg in config.workers.items():
            if wcfg.model and "/" not in wcfg.model:
                errors.append(f"worker '{wid}' model must be 'provider/model' format, got: {wcfg.model}")

        # Check providers
        for pid, pcfg in config.providers.items():
            api_key = pcfg.get("api_key", "")
            if api_key.startswith("${") and api_key.endswith("}"):
                env_var = api_key[2:-1]
                import os
                if not os.environ.get(env_var):
                    warnings.append(f"provider '{pid}' api_key env var ${env_var} is not set")

        # Print results
        if errors:
            print("Validation FAILED:")
            for e in errors:
                print(f"  ERROR: {e}")
            sys.exit(1)

        if warnings:
            print("Validation passed with warnings:")
            for w in warnings:
                print(f"  WARNING: {w}")
        else:
            print("Configuration is valid!")

        print(f"  Conductor: {config.conductor_model}")
        print(f"  Workers:   {len(config.workers)}")
        print(f"  Providers: {len(config.providers)}")
        print(f"  Pool:      {config.pool.instances} instances of {config.pool.model}")

    except Exception as e:
        print(f"Validation FAILED: {e}")
        sys.exit(1)


def cmd_run(args: argparse.Namespace) -> None:
    """Run a one-shot task."""
    message = getattr(args, "message", None)
    if not message:
        print("Error: Message required. Usage: kantorku run 'your task description'")
        sys.exit(1)

    async def _run() -> None:
        from kantorku.office import Office

        config_path = getattr(args, "config", None)
        if config_path:
            office = Office.from_config(config_path)
        else:
            office = Office()

        await office.initialize()

        auto_accept = getattr(args, "auto_accept", False)
        result = await office.run(message, auto_accept=auto_accept)
        print(json.dumps(result, indent=2, default=str))

        await office.shutdown()

    asyncio.run(_run())


def cmd_version(args: argparse.Namespace) -> None:
    """Show kantorku version."""
    from kantorku import __version__
    print(f"kantorku v{__version__}")


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="kantorku",
        description="kantorku — Kantor digital yang sesungguhnya",
    )
    parser.add_argument("--config", "-c", help="Path to kantorku.toml")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # serve
    serve_parser = subparsers.add_parser("serve", help="Start the kantorku server")
    serve_parser.add_argument("--host", default="0.0.0.0", help="Host to bind")
    serve_parser.add_argument("--port", "-p", type=int, default=8000, help="Port to bind")
    serve_parser.add_argument("--reload", action="store_true", help="Enable auto-reload")

    # init
    init_parser = subparsers.add_parser("init", help="Scaffold a new kantorku project")
    init_parser.add_argument("name", nargs="?", default="my-office", help="Project directory name")

    # worker list
    subparsers.add_parser("worker-list", help="List available workers")

    # config validate
    subparsers.add_parser("config-validate", help="Validate kantorku.toml")

    # run
    run_parser = subparsers.add_parser("run", help="Run a one-shot task")
    run_parser.add_argument("message", help="Task description")
    run_parser.add_argument("--auto-accept", "-y", action="store_true", help="Auto-accept contract")

    # version
    subparsers.add_parser("version", help="Show version")

    args = parser.parse_args()

    if args.command == "serve":
        cmd_serve(args)
    elif args.command == "init":
        cmd_init(args)
    elif args.command == "worker-list":
        cmd_worker_list(args)
    elif args.command == "config-validate":
        cmd_config_validate(args)
    elif args.command == "run":
        cmd_run(args)
    elif args.command == "version":
        cmd_version(args)
    else:
        # Default: start server
        cmd_serve(args)


if __name__ == "__main__":
    main()
