#!/usr/bin/env bash
set -euo pipefail

ARG0_DIR="${1:-$HOME/.codex/tmp/arg0/codex-arg0GInYml}"
UPSTREAM_BIN="${2:-$HOME/.vscode-oss/extensions/openai.chatgpt-26.409.20454-linux-x64/bin/linux-x86_64/codex}"
MODEL="${CODEX_DEFAULT_MODEL:-gpt-5.3-codex}"
REASONING="${CODEX_DEFAULT_REASONING_EFFORT:-medium}"
CACHE_PATH="${CODEX_MODELS_CACHE_PATH:-$HOME/.codex/models_cache.json}"

mkdir -p "$ARG0_DIR"

cat > "$ARG0_DIR/codex-wrapper" <<EOF
#!/usr/bin/env bash
set -euo pipefail
export CODEX_HOME="$HOME/.codex"
export CODEX_DEFAULT_MODEL="$MODEL"
export CODEX_DEFAULT_REASONING_EFFORT="$REASONING"
exec "$UPSTREAM_BIN" "\$@"
EOF
chmod +x "$ARG0_DIR/codex-wrapper"

ln -sfn "$ARG0_DIR/codex-wrapper" "$ARG0_DIR/apply_patch"
ln -sfn "$ARG0_DIR/codex-wrapper" "$ARG0_DIR/applypatch"
ln -sfn "$ARG0_DIR/codex-wrapper" "$ARG0_DIR/codex-execve-wrapper"
ln -sfn "$ARG0_DIR/codex-wrapper" "$ARG0_DIR/codex-linux-sandbox"
ln -sfn "$UPSTREAM_BIN" "$ARG0_DIR/codex-upstream"

cat > "$ARG0_DIR/.runtime-note" <<'EOF'
This directory is runtime-generated by Codex/extension wrappers.
Use .codex/skills/setup/scripts/codex-arg0-ensure.sh to re-apply local wrapper defaults.
EOF

echo "arg0 wrapper ensured at: $ARG0_DIR"

# Keep models cache instruction payload minimal; runtime can refresh this file.
if [ -f "$CACHE_PATH" ]; then
  node -e '
const fs=require("fs");
const p=process.argv[1];
const d=JSON.parse(fs.readFileSync(p,"utf8"));
if(Array.isArray(d.models)){
  for(const m of d.models){
    if(typeof m.base_instructions==="string") m.base_instructions="";
    if(!m.model_messages || typeof m.model_messages!=="object") m.model_messages={};
    if(typeof m.model_messages.instructions_template==="string") m.model_messages.instructions_template="";
    if(m.model_messages.instructions_variables && typeof m.model_messages.instructions_variables==="object"){
      m.model_messages.instructions_variables={};
    }
    if(m.slug==="gpt-5.3-codex"){
      m.default_reasoning_level="medium";
      m.supported_reasoning_levels=[{effort:"medium",description:"Balances speed and reasoning depth for everyday tasks"}];
    }
  }
}
fs.writeFileSync(p, JSON.stringify(d));
' "$CACHE_PATH"
  echo "models cache sanitized at: $CACHE_PATH"
fi
