import { WorkerIdentity } from './types';

export const WORKERS: WorkerIdentity[] = [
  {
    id: 'intake',
    model: 'meta/llama4-scout',
    squad: 'intake',
    role: 'Message Parser',
    skill_md: 'Classifies and structures incoming client messages',
    personality: 'Quick and efficient',
    emoji: '📋',
    color: '#6366f1',
    status: 'idle',
  },
  {
    id: 'scout',
    model: 'google/gemma-3-27b',
    squad: 'research',
    role: 'Information Scout',
    skill_md: 'Researches and gathers information',
    personality: 'Curious explorer',
    emoji: '🔍',
    color: '#22c55e',
    status: 'idle',
  },
  {
    id: 'sentinel',
    model: 'anthropic/claude-haiku-4',
    squad: 'quality',
    role: 'Quality Sentinel',
    skill_md: 'Logs lessons and ensures quality',
    personality: 'Vigilant guardian',
    emoji: '🛡️',
    color: '#ef4444',
    status: 'idle',
  },
  {
    id: 'coder_backend',
    model: 'minimax/minimax-m2-7',
    squad: 'engineering',
    role: 'Backend Developer',
    skill_md: 'Implements backend logic, APIs, databases',
    personality: 'Pragmatic builder',
    emoji: '⚙️',
    color: '#3b82f6',
    status: 'idle',
  },
  {
    id: 'coder_frontend',
    model: 'openai/gpt-4.1-mini',
    squad: 'engineering',
    role: 'Frontend Developer',
    skill_md: 'Builds UI components and interfaces',
    personality: 'Creative designer',
    emoji: '🎨',
    color: '#ec4899',
    status: 'idle',
  },
  {
    id: 'coder_wiring',
    model: 'openai/codex-5.3',
    squad: 'engineering',
    role: 'Integration Engineer',
    skill_md: 'Wires APIs, WebSocket, MCP integrations',
    personality: 'System connector',
    emoji: '🔌',
    color: '#f59e0b',
    status: 'idle',
  },
  {
    id: 'verifier_engineer',
    model: 'google/gemini-2.5-pro',
    squad: 'verification',
    role: 'Code Verifier',
    skill_md: 'Verifies code quality and correctness',
    personality: 'Detail-oriented checker',
    emoji: '✅',
    color: '#10b981',
    status: 'idle',
  },
  {
    id: 'verifier_designer',
    model: 'google/gemini-2.5-pro',
    squad: 'verification',
    role: 'Design Verifier',
    skill_md: 'Verifies UI/UX design quality',
    personality: 'Aesthetic critic',
    emoji: '👁️',
    color: '#8b5cf6',
    status: 'idle',
  },
  {
    id: 'debugger',
    model: 'xai/grok-3',
    squad: 'engineering',
    role: 'Debugger',
    skill_md: 'Finds and fixes bugs',
    personality: 'Patient detective',
    emoji: '🐛',
    color: '#f97316',
    status: 'idle',
  },
  {
    id: 'auditor',
    model: 'anthropic/claude-sonnet-4',
    squad: 'quality',
    role: 'Security Auditor',
    skill_md: 'Audits security and compliance',
    personality: 'Thorough inspector',
    emoji: '🔒',
    color: '#dc2626',
    status: 'idle',
  },
  {
    id: 'scribe',
    model: 'openai/gpt-4.1-nano',
    squad: 'documentation',
    role: 'Documentation Writer',
    skill_md: 'Writes documentation and comments',
    personality: 'Clear communicator',
    emoji: '📝',
    color: '#0ea5e9',
    status: 'idle',
  },
  {
    id: 'narrator',
    model: 'anthropic/claude-opus-4-6',
    squad: 'documentation',
    role: 'Narrator',
    skill_md: 'Creates narratives and presentations',
    personality: 'Storyteller',
    emoji: '📖',
    color: '#7c3aed',
    status: 'idle',
  },
  {
    id: 'summarizer',
    model: 'meta/llama4-maverick',
    squad: 'documentation',
    role: 'Summarizer',
    skill_md: 'Summarizes discussions and outputs',
    personality: 'Concise synthesizer',
    emoji: '📊',
    color: '#14b8a6',
    status: 'idle',
  },
];

export const SQUADS = [
  { id: 'intake', label: 'Intake', color: '#6366f1' },
  { id: 'research', label: 'Research', color: '#22c55e' },
  { id: 'engineering', label: 'Engineering', color: '#3b82f6' },
  { id: 'verification', label: 'Verification', color: '#10b981' },
  { id: 'quality', label: 'Quality', color: '#ef4444' },
  { id: 'documentation', label: 'Documentation', color: '#0ea5e9' },
];

export const MEMORY_RINGS = [
  { ring: 1, label: 'Ring 1 — Session', description: 'Current session context, task results, contract state', size: 0, color: '#06b6d4' },
  { ring: 2, label: 'Ring 2 — Episodes', description: 'Cross-session episodes, lessons learned, analytics', size: 0, color: '#f59e0b' },
  { ring: 3, label: 'Ring 3 — Knowledge', description: 'Long-term knowledge, vector search, organizational memory', size: 0, color: '#ec4899' },
];

export const CONTRACT_STATE_LABELS: Record<ContractState, string> = {
  idle: 'Idle',
  manager_thinking: 'Manager Thinking...',
  team_consult: 'Team Consult',
  clarifying: 'Clarifying Requirements',
  contract_presented: 'Contract Ready',
  team_review: 'Team Review',
  todo_review: 'TODO Review',
  client_feedback: 'Client Feedback',
  working: 'Working',
  done: 'Done',
  failed: 'Failed',
};

export const CONTRACT_STATE_COLORS: Record<ContractState, string> = {
  idle: 'border-slate-600/50 text-slate-400 bg-slate-800/30',
  manager_thinking: 'border-amber-500/40 text-amber-300 bg-amber-500/10',
  team_consult: 'border-violet-500/40 text-violet-300 bg-violet-500/10',
  clarifying: 'border-amber-500/40 text-amber-300 bg-amber-500/10',
  contract_presented: 'border-cyan-500/40 text-cyan-300 bg-cyan-500/10',
  team_review: 'border-violet-500/40 text-violet-300 bg-violet-500/10',
  todo_review: 'border-teal-500/40 text-teal-300 bg-teal-500/10',
  client_feedback: 'border-amber-500/40 text-amber-300 bg-amber-500/10',
  working: 'border-cyan-500/40 text-cyan-300 bg-cyan-500/10',
  done: 'border-green-500/40 text-green-300 bg-green-500/10',
  failed: 'border-red-500/40 text-red-300 bg-red-500/10',
};

export const MESSAGE_TYPE_COLORS: Record<string, string> = {
  speak: '#94a3b8',
  concern: '#ef4444',
  suggestion: '#22c55e',
  question: '#f59e0b',
  response: '#3b82f6',
  agreement: '#10b981',
  disagreement: '#dc2626',
  info: '#06b6d4',
  manager_summary: '#8b5cf6',
  manager_decision: '#ec4899',
};

export const MESSAGE_TYPE_ICONS: Record<string, string> = {
  speak: '💬',
  concern: '⚠️',
  suggestion: '💡',
  question: '❓',
  response: '↩️',
  agreement: '✅',
  disagreement: '❌',
  info: 'ℹ️',
  manager_summary: '📋',
  manager_decision: '✅',
};

import type { ContractState } from './types';
