"""
kantorku CLI — Command-line interface.

Commands:
    kantorku serve                Start the server (default)
    kantorku tui                  Launch the TUI for coders
    kantorku init                 Scaffold a new kantorku project
    kantorku worker create        Create a new plug-and-play worker
    kantorku worker add           Add a worker from an existing directory
    kantorku worker validate      Validate a worker directory
    kantorku worker list          List available workers
    kantorku config validate      Validate kantorku.toml
    kantorku run                  Run a one-shot task
    kantorku version              Show version
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path


def cmd_serve(args: argparse.Namespace) -> None:
    """Start the kantorku server."""
    import uvicorn
    from kantorku.interface.server import create_office

    config_path = getattr(args, "config", None)
    office = create_office(config_path)

    uvicorn.run(
        "kantorku.interface.server:app",
        host=getattr(args, "host", "0.0.0.0"),
        port=getattr(args, "port", 8000),
        reload=getattr(args, "reload", False),
        lifespan="on",
    )


def cmd_init(args: argparse.Namespace) -> None:
    """Scaffold a new kantorku project."""
    project_dir = Path(getattr(args, "name", "my-office"))
    project_dir.mkdir(parents=True, exist_ok=True)

    # Create kantorku.toml
    toml_content = '''# kantorku configuration
# Generated by `kantorku init`

[conductor]
model = "anthropic/claude-opus-4-6"

[providers.anthropic]
api_key = "${ANTHROPIC_API_KEY}"

[providers.ollama]
base_url = "http://localhost:11434"

[workers.coder_frontend]
model = "anthropic/claude-sonnet-4-6"
squad = "coding"
role = "React/CSS/UI specialist"

[workers.coder_backend]
model = "ollama/llama3"
squad = "coding"
role = "Python/Rust/Systems specialist"

[workers.intake]
model = "ollama/llama3"
squad = "translation"
role = "Message parser"

[workers.narrator]
model = "ollama/llama3"
squad = "translation"
role = "Output formatter"

[pool]
model = "ollama/llama3"
instances = 1

[memory]
ring1_path = "data/ring1.duckdb"
ring2_path = "data/ring2.db"
ring3_enabled = false

[server]
host = "0.0.0.0"
port = 8000
'''

    (project_dir / "kantorku.toml").write_text(toml_content)

    # Create data directory
    (project_dir / "data").mkdir(exist_ok=True)

    # Create custom workers directory with README
    workers_dir = project_dir / "workers"
    workers_dir.mkdir(exist_ok=True)
    (workers_dir / ".gitkeep").touch()

    # Create a simple example
    example_content = '''"""Example: Using kantorku programmatically."""
import asyncio
from kantorku import Office, Hooks, HookType

async def main():
    # Create office with hooks
    hooks = Hooks()

    @hooks.on(HookType.ON_TASK_COMPLETED)
    async def on_done(event):
        print(f"Task completed: {event.get('task_id', 'unknown')}")

    office = Office(hooks=hooks)

    # Configure providers
    office.configure_provider("ollama", base_url="http://localhost:11434")

    # Hire workers
    office.hire_worker("coder_backend", model="ollama/llama3", role="Backend developer")

    # Initialize
    await office.initialize()

    # Run a task
    result = await office.run("Write a Python function to calculate fibonacci", auto_accept=True)
    print(result)

    await office.shutdown()

if __name__ == "__main__":
    asyncio.run(main())
'''

    (project_dir / "example.py").write_text(example_content)

    print(f"Created kantorku project in ./{project_dir}/")
    print(f"  - {project_dir}/kantorku.toml  (configuration)")
    print(f"  - {project_dir}/data/          (memory storage)")
    print(f"  - {project_dir}/workers/       (custom workers — drop worker folders here!)")
    print(f"  - {project_dir}/example.py     (example script)")
    print()
    print("Next steps:")
    print(f"  1. cd {project_dir}")
    print("  2. Edit kantorku.toml with your API keys")
    print("  3. Create a custom worker: kantorku worker create my_worker")
    print("  4. Run: kantorku serve --config kantorku.toml")


# ─────────────────────────────────────────────────
#  Worker Commands
# ─────────────────────────────────────────────────

def cmd_worker_create(args: argparse.Namespace) -> None:
    """Create a new plug-and-play worker."""
    from kantorku.worker.generator import WorkerGenerator

    worker_id = getattr(args, "name", None)
    if not worker_id:
        print("Error: Worker name is required. Usage: kantorku worker create <name>")
        sys.exit(1)

    # Validate name
    if not worker_id.replace("_", "").isalnum():
        print(f"Error: Worker name '{worker_id}' must be alphanumeric + underscores only")
        sys.exit(1)

    base_dir = Path(getattr(args, "base_dir", "workers"))
    model = getattr(args, "model", "ollama/llama3") or "ollama/llama3"
    squad = getattr(args, "squad", "support") or "support"
    role = getattr(args, "role", "") or ""
    capabilities = getattr(args, "capabilities", "") or ""
    description = getattr(args, "description", "") or ""
    overwrite = getattr(args, "overwrite", False)

    cap_list = [c.strip() for c in capabilities.split(",") if c.strip()] if capabilities else []
    tag_list = [t.strip() for t in getattr(args, "tags", "").split(",") if t.strip()] if getattr(args, "tags", "") else []
    category = getattr(args, "category", "") or ""
    subcategory = getattr(args, "subcategory", "") or ""
    display_name = getattr(args, "display_name", "") or ""

    gen = WorkerGenerator()
    try:
        worker_dir = gen.create(
            worker_id=worker_id,
            base_dir=base_dir,
            model=model,
            squad=squad,
            category=category,
            subcategory=subcategory,
            display_name=display_name,
            role=role,
            capabilities=cap_list,
            tags=tag_list,
            description=description,
            overwrite=overwrite,
        )
        print(f"Created worker: {worker_id}")
        print()
        print(f"  {worker_dir}/")
        print(f"  ├── plugin.json    ← metadata (id, model, squad, capabilities)")
        print(f"  ├── SKILL.md       ← system prompt for the LLM")
        print(f"  ├── worker.py      ← custom BaseWorker subclass")
        print(f"  └── __init__.py    ← re-exports for Python import")
        print()
        print("Next steps:")
        print(f"  1. Edit {worker_dir}/SKILL.md to define the worker's expertise")
        print(f"  2. Edit {worker_dir}/worker.py to add custom logic")
        print(f"  3. Edit {worker_dir}/plugin.json to set model/squad/role")
        print(f"  4. The worker will be auto-discovered from workers/ at startup!")
        print()
        print("Quick test:")
        print(f"  kantorku worker validate {worker_dir}")
        print(f"  kantorku worker list")

    except FileExistsError as e:
        print(f"Error: {e}")
        print("Use --overwrite to replace existing files.")
        sys.exit(1)
    except ValueError as e:
        print(f"Error: {e}")
        sys.exit(1)


def cmd_worker_add(args: argparse.Namespace) -> None:
    """Add a worker from an existing directory (validates first)."""
    from kantorku.worker.registry import WorkerRegistry
    from kantorku.events.bus import EventBus
    from kantorku.providers.router import ProviderRouter

    path = getattr(args, "path", None)
    if not path:
        print("Error: Worker directory path required. Usage: kantorku worker add <path>")
        sys.exit(1)

    worker_path = Path(path).resolve()
    if not worker_path.exists():
        print(f"Error: Directory not found: {worker_path}")
        sys.exit(1)

    # Validate first
    router = ProviderRouter()
    bus = EventBus()
    registry = WorkerRegistry(router=router, bus=bus)

    messages = registry.validate_worker_dir(worker_path)
    errors = [m for m in messages if not m.startswith("[WARNING]") and not m.startswith("[INFO]")]
    warnings = [m for m in messages if m.startswith("[WARNING]")]
    infos = [m for m in messages if m.startswith("[INFO]")]

    if errors:
        print("Worker validation FAILED:")
        for e in errors:
            print(f"  ERROR: {e}")
        sys.exit(1)

    if warnings:
        print("Worker validation passed with warnings:")
        for w in warnings:
            print(f"  {w}")

    for i in infos:
        print(f"  {i}")

    # Show what was found
    try:
        identity = registry.hot_plug(
            worker_path,
            model=getattr(args, "model", "") or "",
            squad=getattr(args, "squad", "") or "",
            role=getattr(args, "role", "") or "",
        )
        print()
        print(f"Worker ready: {identity.id}")
        print(f"  Model: {identity.model or 'not set'}")
        print(f"  Squad: {identity.squad or 'not set'}")
        print(f"  Role:  {identity.role or 'not set'}")
        print(f"  Has custom class: {'Yes' if identity.class_path else 'No (uses SKILL.md + BaseWorker)'}")
        print()
        print("To use in kantorku.toml, add:")
        print(f'  [workers.{identity.id}]')
        print(f'  model = "{identity.model or "ollama/llama3"}"')
        print(f'  squad = "{identity.squad or "support"}"')
        print(f'  role = "{identity.role or identity.id.replace("_", " ").title()}"')

    except Exception as e:
        print(f"Error adding worker: {e}")
        sys.exit(1)


def cmd_worker_validate(args: argparse.Namespace) -> None:
    """Validate a worker directory."""
    from kantorku.worker.registry import WorkerRegistry
    from kantorku.events.bus import EventBus
    from kantorku.providers.router import ProviderRouter

    path = getattr(args, "path", None)
    if not path:
        print("Error: Worker directory path required. Usage: kantorku worker validate <path>")
        sys.exit(1)

    worker_path = Path(path).resolve()
    router = ProviderRouter()
    bus = EventBus()
    registry = WorkerRegistry(router=router, bus=bus)

    messages = registry.validate_worker_dir(worker_path)
    errors = [m for m in messages if not m.startswith("[WARNING]") and not m.startswith("[INFO]")]
    warnings = [m for m in messages if m.startswith("[WARNING]")]
    infos = [m for m in messages if m.startswith("[INFO]")]

    if errors:
        print(f"Worker validation FAILED: {worker_path}")
        for e in errors:
            print(f"  ERROR: {e}")
        sys.exit(1)

    if warnings or infos:
        print(f"Worker validation: {worker_path}")
        for w in warnings:
            print(f"  {w}")
        for i in infos:
            print(f"  {i}")
        if not errors:
            print()
            print("Status: VALID (with notes above)")
    else:
        print(f"Worker validation: {worker_path}")
        print("  Status: VALID")
        print("  All checks passed!")

    # Show worker details
    try:
        from kantorku.worker.identity import WorkerIdentity
        identity = WorkerIdentity.from_directory(worker_path)
        print()
        print(f"  ID:           {identity.id}")
        print(f"  Model:        {identity.model or 'not set'}")
        print(f"  Squad:        {identity.squad or 'not set'}")
        print(f"  Role:         {identity.role or 'not set'}")
        print(f"  Capabilities: {identity.capabilities or 'none'}")
        print(f"  Has SKILL.md: {'Yes' if identity.skill_md else 'No'}")
        print(f"  Has worker.py: {'Yes' if identity.class_path else 'No'}")
        if identity.class_path:
            cls = identity.resolve_worker_class()
            print(f"  Class:        {cls.__name__ if cls else 'unresolved'}")
    except Exception:
        pass


def cmd_worker_list(args: argparse.Namespace) -> None:
    """List available workers."""
    from kantorku.worker.registry import WorkerRegistry
    from kantorku.events.bus import EventBus
    from kantorku.providers.router import ProviderRouter

    router = ProviderRouter()
    bus = EventBus()
    registry = WorkerRegistry(router=router, bus=bus)

    # Discover built-in workers
    builtin_dir = Path(__file__).parent.parent / "workers"
    if builtin_dir.exists():
        registry.discover_workers(builtin_dir)

    # Discover external workers from config
    config_path = getattr(args, "config", None)
    if config_path:
        # From config file's parent workers/ directory
        external_dir = Path(config_path).parent / "workers"
        if external_dir.exists():
            registry.discover_workers(external_dir)

        # Also load from config itself
        try:
            from kantorku.config.settings import KantorkuConfig
            config = KantorkuConfig.from_toml(config_path)
            workers_config = {
                wid: {"model": w.model, "squad": w.squad, "role": w.role}
                for wid, w in config.workers.items()
            }
            registry.discover_from_config(workers_config)
        except Exception:
            pass
    else:
        # Check current directory
        cwd_workers = Path("workers")
        if cwd_workers.exists():
            registry.discover_workers(cwd_workers)

    workers = registry.list_workers()

    if not workers:
        print("No workers found.")
        print()
        print("Create one with: kantorku worker create my_worker")
        return

    # Group by category (or squad if no category)
    squads: dict[str, list[dict]] = {}
    for w in workers:
        squad = w.get("category", "") or w.get("squad", "unknown") or "uncategorized"
        if squad not in squads:
            squads[squad] = []
        squads[squad].append(w)

    total = len(workers)
    custom_count = sum(1 for w in workers if w.get("has_custom_class"))
    builtin_count = total - custom_count

    print(f"Available workers ({total} total: {builtin_count} built-in, {custom_count} custom):\n")
    for squad, members in sorted(squads.items()):
        print(f"  [{squad}]")
        for w in members:
            model = w.get("model", "N/A") or "N/A"
            status = w.get("status", "N/A")
            display = w.get("display_name", "") or w.get("role", "")
            subcat = w.get("subcategory", "")
            custom = " (custom)" if w.get("has_custom_class") else ""
            subcat_label = f"/{subcat}" if subcat else ""
            print(f"    - {w['id']:25s} [{display}{subcat_label}] model={model:30s}{custom}")
        print()


# ─────────────────────────────────────────────────
#  Config & Run Commands
# ─────────────────────────────────────────────────

def cmd_config_validate(args: argparse.Namespace) -> None:
    """Validate a kantorku.toml configuration file."""
    config_path = getattr(args, "config", None)
    if not config_path:
        print("Error: --config path required for validation")
        sys.exit(1)

    path = Path(config_path)
    if not path.exists():
        print(f"Error: Config file not found: {config_path}")
        sys.exit(1)

    try:
        from kantorku.config.settings import KantorkuConfig
        config = KantorkuConfig.from_toml(config_path)
        config.resolve_env_vars()

        errors = []
        warnings = []

        # Check conductor model
        if not config.conductor_model:
            errors.append("conductor.model is required")
        elif "/" not in config.conductor_model:
            errors.append(f"conductor.model must be 'provider/model' format, got: {config.conductor_model}")

        # Check workers
        if not config.workers:
            warnings.append("No workers configured")

        for wid, wcfg in config.workers.items():
            if wcfg.model and "/" not in wcfg.model:
                errors.append(f"worker '{wid}' model must be 'provider/model' format, got: {wcfg.model}")

        # Check providers
        for pid, pcfg in config.providers.items():
            api_key = pcfg.get("api_key", "")
            if api_key.startswith("${") and api_key.endswith("}"):
                env_var = api_key[2:-1]
                import os
                if not os.environ.get(env_var):
                    warnings.append(f"provider '{pid}' api_key env var ${env_var} is not set")

        # Print results
        if errors:
            print("Validation FAILED:")
            for e in errors:
                print(f"  ERROR: {e}")
            sys.exit(1)

        if warnings:
            print("Validation passed with warnings:")
            for w in warnings:
                print(f"  WARNING: {w}")
        else:
            print("Configuration is valid!")

        print(f"  Conductor: {config.conductor_model}")
        print(f"  Workers:   {len(config.workers)}")
        print(f"  Providers: {len(config.providers)}")
        print(f"  Pool:      {config.pool.instances} instances of {config.pool.model}")

    except Exception as e:
        print(f"Validation FAILED: {e}")
        sys.exit(1)


def cmd_run(args: argparse.Namespace) -> None:
    """Run a one-shot task."""
    message = getattr(args, "message", None)
    if not message:
        print("Error: Message required. Usage: kantorku run 'your task description'")
        sys.exit(1)

    async def _run() -> None:
        from kantorku.office import Office

        config_path = getattr(args, "config", None)
        if config_path:
            office = Office.from_config(config_path)
        else:
            office = Office()

        await office.initialize()

        auto_accept = getattr(args, "auto_accept", False)
        result = await office.run(message, auto_accept=auto_accept)
        print(json.dumps(result, indent=2, default=str))

        await office.shutdown()

    asyncio.run(_run())


def cmd_tui(args: argparse.Namespace) -> None:
    """Launch the KantorKu TUI for coders."""
    try:
        from kantorku.tui.app import KantorKuTUI, EmbeddedKantorKuTUI
    except ImportError as e:
        print("Error: TUI dependencies not installed.")
        print("  Install with: pip install kantorku[tui]")
        print(f"  Details: {e}")
        sys.exit(1)

    server_url = getattr(args, "url", None) or "http://localhost:8000"
    config_path = getattr(args, "config", None)
    embedded = getattr(args, "embedded", False)

    if embedded:
        # Embedded mode — run Office directly in-process
        app = EmbeddedKantorKuTUI(config_path=config_path)
    else:
        # Remote mode — connect to a running server
        app = KantorKuTUI(server_url=server_url, config_path=config_path)

    app.run()


def cmd_version(args: argparse.Namespace) -> None:
    """Show kantorku version."""
    from kantorku import __version__
    print(f"kantorku v{__version__}")


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="kantorku",
        description="kantorku — Kantor digital yang sesungguhnya",
    )
    parser.add_argument("--config", "-c", help="Path to kantorku.toml")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # serve
    serve_parser = subparsers.add_parser("serve", help="Start the kantorku server")
    serve_parser.add_argument("--host", default="0.0.0.0", help="Host to bind")
    serve_parser.add_argument("--port", "-p", type=int, default=8000, help="Port to bind")
    serve_parser.add_argument("--reload", action="store_true", help="Enable auto-reload")

    # init
    init_parser = subparsers.add_parser("init", help="Scaffold a new kantorku project")
    init_parser.add_argument("name", nargs="?", default="my-office", help="Project directory name")

    # worker subcommand group
    worker_parser = subparsers.add_parser("worker", help="Worker management commands")
    worker_subparsers = worker_parser.add_subparsers(dest="worker_command", help="Worker commands")

    # worker create
    create_parser = worker_subparsers.add_parser(
        "create", help="Create a new plug-and-play worker",
        aliases=["new"],
    )
    create_parser.add_argument("name", help="Worker ID (alphanumeric + underscores)")
    create_parser.add_argument("--model", "-m", default="ollama/llama3", help="LLM model (provider/model)")
    create_parser.add_argument("--squad", "-s", default="support",
                               choices=["coding", "verification", "support", "translation"],
                               help="Squad assignment")
    create_parser.add_argument("--role", "-r", default="", help="Role description")
    create_parser.add_argument("--capabilities", "-cap", default="", help="Comma-separated capabilities")
    create_parser.add_argument("--category", "-cat", default="", help="Top-level category (coding, verification, support, translation)")
    create_parser.add_argument("--subcategory", "-sub", default="", help="Sub-category (e.g. frontend, backend, debugging)")
    create_parser.add_argument("--display-name", "-dn", default="", help="Human-friendly display name")
    create_parser.add_argument("--tags", "-t", default="", help="Comma-separated tags for AI agent organization")
    create_parser.add_argument("--description", "-d", default="", help="Short description")
    create_parser.add_argument("--base-dir", default="workers", help="Parent directory for workers")
    create_parser.add_argument("--overwrite", "-f", action="store_true", help="Overwrite existing files")

    # worker add
    add_parser = worker_subparsers.add_parser("add", help="Add a worker from an existing directory")
    add_parser.add_argument("path", help="Path to worker directory")
    add_parser.add_argument("--model", "-m", default="", help="Override model")
    add_parser.add_argument("--squad", "-s", default="", help="Override squad")
    add_parser.add_argument("--role", "-r", default="", help="Override role")

    # worker validate
    validate_parser = worker_subparsers.add_parser("validate", help="Validate a worker directory")
    validate_parser.add_argument("path", help="Path to worker directory")

    # worker list
    worker_subparsers.add_parser("list", help="List available workers")

    # config validate
    subparsers.add_parser("config-validate", help="Validate kantorku.toml")

    # run
    run_parser = subparsers.add_parser("run", help="Run a one-shot task")
    run_parser.add_argument("message", help="Task description")
    run_parser.add_argument("--auto-accept", "-y", action="store_true", help="Auto-accept contract")

    # tui
    tui_parser = subparsers.add_parser("tui", help="Launch the TUI for coders")
    tui_parser.add_argument("--url", "-u", default="http://localhost:8000",
                             help="Server URL (default: http://localhost:8000)")
    tui_parser.add_argument("--embedded", "-e", action="store_true",
                             help="Run Office in-process (no server needed)")

    # version
    subparsers.add_parser("version", help="Show version")

    args = parser.parse_args()

    if args.command == "serve":
        cmd_serve(args)
    elif args.command == "init":
        cmd_init(args)
    elif args.command == "worker":
        if args.worker_command in ("create", "new"):
            cmd_worker_create(args)
        elif args.worker_command == "add":
            cmd_worker_add(args)
        elif args.worker_command == "validate":
            cmd_worker_validate(args)
        elif args.worker_command == "list":
            cmd_worker_list(args)
        else:
            worker_parser.print_help()
    elif args.command == "worker-list":
        # Backwards compat
        cmd_worker_list(args)
    elif args.command == "config-validate":
        cmd_config_validate(args)
    elif args.command == "run":
        cmd_run(args)
    elif args.command == "tui":
        cmd_tui(args)
    elif args.command == "version":
        cmd_version(args)
    else:
        # Default: start server
        cmd_serve(args)


if __name__ == "__main__":
    main()
