#!/usr/bin/env bash
set -euo pipefail

ARG0_DIR="${1:-$HOME/.codex/tmp/arg0/codex-arg0GInYml}"
EXT_DIR_ROOT="${CODEX_VSCODE_EXT_ROOT:-$HOME/.vscode-oss/extensions}"
MODEL="${CODEX_DEFAULT_MODEL:-gpt-5.3-codex}"
REASONING="${CODEX_DEFAULT_REASONING_EFFORT:-medium}"

find_upstream_bin() {
  local pattern="openai.chatgpt-*-linux-x64"
  local latest_dir
  latest_dir="$(ls -d "$EXT_DIR_ROOT"/$pattern 2>/dev/null | sort -V | tail -n 1 || true)"
  if [ -z "$latest_dir" ]; then
    return 1
  fi

  local bin="$latest_dir/bin/linux-x86_64/codex"
  if [ ! -x "$bin" ]; then
    return 1
  fi

  printf '%s\n' "$bin"
}

UPSTREAM_BIN="${2:-}"
if [ -z "$UPSTREAM_BIN" ]; then
  if ! UPSTREAM_BIN="$(find_upstream_bin)"; then
    echo "error: unable to locate codex upstream binary under: $EXT_DIR_ROOT" >&2
    echo "hint: pass explicit path as arg2, e.g. bash .codex/tools/codex-arg0-bootstrap.sh <arg0_dir> <upstream_bin>" >&2
    exit 1
  fi
fi

mkdir -p "$ARG0_DIR"

cat > "$ARG0_DIR/codex-wrapper" <<WRAP
#!/usr/bin/env bash
set -euo pipefail
export CODEX_HOME="$HOME/.codex"
export CODEX_DEFAULT_MODEL="$MODEL"
export CODEX_DEFAULT_REASONING_EFFORT="$REASONING"
exec "$UPSTREAM_BIN" "\$@"
WRAP
chmod +x "$ARG0_DIR/codex-wrapper"

ln -sfn "$ARG0_DIR/codex-wrapper" "$ARG0_DIR/apply_patch"
ln -sfn "$ARG0_DIR/codex-wrapper" "$ARG0_DIR/applypatch"
ln -sfn "$ARG0_DIR/codex-wrapper" "$ARG0_DIR/codex-execve-wrapper"
ln -sfn "$ARG0_DIR/codex-wrapper" "$ARG0_DIR/codex-linux-sandbox"
ln -sfn "$UPSTREAM_BIN" "$ARG0_DIR/codex-upstream"

cat > "$ARG0_DIR/.runtime-note" <<'NOTE'
This directory is runtime-generated by Codex/extension wrappers.
Use .codex/skills/setup/scripts/codex-arg0-ensure.sh to re-apply local wrapper defaults.
If that script is missing, use .codex/tools/codex-arg0-bootstrap.sh.
NOTE

echo "arg0 bootstrap ready: $ARG0_DIR"
echo "upstream binary: $UPSTREAM_BIN"
